### ISSUE TITLE
furniture "cartoonist's set"  pattern change

### ISSUE THREAD

**Issue by HuskyHsu** [alexislours/translation-sheet-data#1]
furniture "cartoonist's set"  pattern change in 1.3.0 version
"Comic plan" > "Comic storyboard"

![image](https://user-images.githubusercontent.com/18141436/86862891-b6d62300-c0fc-11ea-8727-751a785d62df.png)
![image](https://user-images.githubusercontent.com/18141436/86862936-c7869900-c0fc-11ea-8b6b-803ebfa8890e.png)

**Comment by alexislours** [comment]
Corrected in [e1ceb632ce9f43ba04498e8a9512e65fe02942f1](https://github.com/alexislours/translation-sheet-data/commit/e1ceb632ce9f43ba04498e8a9512e65fe02942f1), thanks for bringing it up.
